
  CREATE TABLE SCHEMA_NAME.PARAMETER
   ("SCHEMA_NAME" VARCHAR2(50 BYTE), 
	"OBJECT_NAME" VARCHAR2(50 BYTE), 
	"OBJECT_TYPE" VARCHAR2(5 BYTE), 
	"FREQUENCY_TYPE" VARCHAR2(12 BYTE), 
	"UPDATE_TIME" VARCHAR2(5 BYTE), 
	"UPDATE_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCHEMA_NAME" ;

   COMMENT ON COLUMN SCHEMA_NAME.PARAMETER.SCHEMA_NAME IS 'Schema name.';
   COMMENT ON COLUMN SCHEMA_NAME.PARAMETER.OBJECT_NAME IS 'Object name.';
   COMMENT ON COLUMN SCHEMA_NAME.PARAMETER.OBJECT_TYPE IS 'Type of object.';
   COMMENT ON COLUMN SCHEMA_NAME.PARAMETER.FREQUENCY_TYPE IS 'The frequency that data is updated.';
   COMMENT ON COLUMN SCHEMA_NAME.PARAMETER.UPDATE_TIME IS 'The hour that the data is going to be updated.';
   COMMENT ON COLUMN SCHEMA_NAME.PARAMETER.UPDATE_TYPE IS 'The kind of update rule.';
   COMMENT ON TABLE SCHEMA_NAME.PARAMETER  IS 'This table contains information about data base default update rules.';


  GRANT SELECT ON SCHEMA_NAME.PARAMETER TO "UserName";
